insert into cars (mark, model, engin, fuel, price, image) values ('Oldsmobile', 'Silhouette', 'V6', 'diisel', 479, '/morbi/odio/odio/elementum/eu.png');
insert into cars (mark, model, engin, fuel, price, image) values ('Suzuki', 'SJ', 'V12', 'diisel', 239, '/vel.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Mazda', 'RX-7', 'V12', 'bensiin', 906, '/vitae/quam/suspendisse.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Ford', 'Windstar', 'V8', 'gaas', 739, '/dapibus/at/diam/nam/tristique/tortor.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Ford', 'Edge', 'V12', 'bensiin', 340, '/quam/fringilla.json');
insert into cars (mark, model, engin, fuel, price, image) values ('Acura', 'TL', 'V12', 'gaas', 223, '/ut/tellus.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Dodge', 'Avenger', 'V8', 'elekter', 596, '/eget.json');
insert into cars (mark, model, engin, fuel, price, image) values ('GMC', 'Safari', 'V12', 'elekter', 698, '/amet.png');
insert into cars (mark, model, engin, fuel, price, image) values ('Saturn', 'L-Series', 'V6', 'bensiin', 413, '/id/nulla/ultrices/aliquet.png');
insert into cars (mark, model, engin, fuel, price, image) values ('Maybach', 'Landaulet', 'V8', 'diisel', 528, '/sit/amet/nulla/quisque.json');
insert into cars (mark, model, engin, fuel, price, image) values ('Isuzu', 'Hombre', 'V12', 'elekter', 702, '/dui/luctus/rutrum/nulla.jsp');
insert into cars (mark, model, engin, fuel, price, image) values ('Acura', 'RL', 'V12', 'bensiin', 291, '/massa.js');
insert into cars (mark, model, engin, fuel, price, image) values ('Audi', 'A8', 'V6', 'bensiin', 342, '/in/eleifend/quam/a/odio.js');
insert into cars (mark, model, engin, fuel, price, image) values ('Pontiac', '6000', 'V8', 'bensiin', 902, '/a/nibh/in/quis/justo/maecenas.jpg');
insert into cars (mark, model, engin, fuel, price, image) values ('Kia', 'Sportage', 'V6', 'gaas', 597, '/vestibulum/rutrum.jpg');
insert into cars (mark, model, engin, fuel, price, image) values ('Chevrolet', 'Express 3500', 'V12', 'bensiin', 350, '/pulvinar/nulla.xml');
insert into cars (mark, model, engin, fuel, price, image) values ('Mercury', 'Sable', 'V6', 'elekter', 569, '/ultrices/enim/lorem/ipsum/dolor/sit/amet.jsp');
insert into cars (mark, model, engin, fuel, price, image) values ('Audi', 'TT', 'V8', 'elekter', 156, '/enim/sit/amet.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Pontiac', 'Bonneville', 'V8', 'bensiin', 318, '/dis/parturient/montes/nascetur/ridiculus/mus/etiam.jpg');
insert into cars (mark, model, engin, fuel, price, image) values ('Honda', 'Accord', 'V6', 'bensiin', 881, '/consequat.jpg');
insert into cars (mark, model, engin, fuel, price, image) values ('Chrysler', 'Sebring', 'V12', 'elekter', 534, '/risus/auctor/sed/tristique.png');
insert into cars (mark, model, engin, fuel, price, image) values ('Chevrolet', 'Lumina', 'V12', 'elekter', 501, '/rhoncus/dui/vel/sem.xml');
insert into cars (mark, model, engin, fuel, price, image) values ('Subaru', 'Justy', 'V6', 'diisel', 111, '/sed/accumsan/felis/ut/at/dolor.jpg');
insert into cars (mark, model, engin, fuel, price, image) values ('Pontiac', 'Tempest', 'V12', 'diisel', 533, '/gravida/nisi.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Bugatti', 'Veyron', 'V12', 'gaas', 907, '/sem/sed/sagittis/nam/congue/risus.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('BMW', 'X5', 'V6', 'gaas', 142, '/rutrum/ac.json');
insert into cars (mark, model, engin, fuel, price, image) values ('Hummer', 'H1', 'V8', 'bensiin', 912, '/cursus/urna/ut.xml');
insert into cars (mark, model, engin, fuel, price, image) values ('Panoz', 'Esperante', 'V12', 'gaas', 820, '/cum/sociis.js');
insert into cars (mark, model, engin, fuel, price, image) values ('Pontiac', 'Grand Prix', 'V8', 'gaas', 186, '/pede/ullamcorper/augue/a/suscipit/nulla.html');
insert into cars (mark, model, engin, fuel, price, image) values ('Lexus', 'LS', 'V6', 'gaas', 123, '/quam/nec/dui/luctus/rutrum/nulla/tellus.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Pontiac', 'Grand Prix', 'V8', 'bensiin', 649, '/risus/praesent/lectus/vestibulum/quam/sapien/varius.png');
insert into cars (mark, model, engin, fuel, price, image) values ('Ford', 'F350', 'V12', 'gaas', 870, '/primis/in/faucibus/orci/luctus/et.jsp');
insert into cars (mark, model, engin, fuel, price, image) values ('Saab', '9-3', 'V6', 'elekter', 112, '/libero.jpg');
insert into cars (mark, model, engin, fuel, price, image) values ('Chevrolet', 'Camaro', 'V12', 'gaas', 314, '/pharetra/magna/ac/consequat/metus.jsp');
insert into cars (mark, model, engin, fuel, price, image) values ('Isuzu', 'Rodeo', 'V6', 'bensiin', 542, '/orci/luctus/et/ultrices/posuere.json');
insert into cars (mark, model, engin, fuel, price, image) values ('MINI', 'Countryman', 'V8', 'gaas', 101, '/lacus.xml');
insert into cars (mark, model, engin, fuel, price, image) values ('GMC', 'Yukon XL 2500', 'V8', 'diisel', 598, '/sed.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Dodge', 'Ram 2500', 'V12', 'gaas', 255, '/ac/est/lacinia/nisi/venenatis/tristique/fusce.aspx');
insert into cars (mark, model, engin, fuel, price, image) values ('Land Rover', 'Range Rover', 'V12', 'elekter', 833, '/convallis/eget/eleifend/luctus/ultricies/eu.js');
insert into cars (mark, model, engin, fuel, price, image) values ('Oldsmobile', 'LSS', 'V8', 'gaas', 135, '/malesuada/in/imperdiet.html');
